### ISSUE TITLE
Error when deleting a user with occ

### ISSUE THREAD

**Issue by Emi94** [nextcloud/circles#211]
When I delete a user with the occ script I get this error:
```
An unhandled exception has been thrown:
Error: Call to a member function getUID() on null in /var/www/nextcloud/apps/circles/lib/Api/v1/Circles.php:185
Stack trace:
#0 /var/www/nextcloud/apps/mindmaps/lib/Db/MindmapMapper.php(131): OCA\Circles\Api\v1\Circles::listCircles(15)
#1 /var/www/nextcloud/apps/mindmaps/lib/AppInfo/Application.php(69): OCA\Mindmaps\Db\MindmapMapper->findAll('test22')
#2 [internal function]: OCA\Mindmaps\AppInfo\Application->OCA\Mindmaps\AppInfo\{closure}(Object(OC\User\User))
#3 /var/www/nextcloud/lib/private/Hooks/EmitterTrait.php(99): call_user_func_array(Object(Closure), Array)
#4 /var/www/nextcloud/lib/private/Hooks/PublicEmitter.php(36): OC\Hooks\BasicEmitter->emit('\\OC\\User', 'postDelete', Array)
#5 /var/www/nextcloud/lib/private/User/User.php(247): OC\Hooks\PublicEmitter->emit('\\OC\\User', 'postDelete', Array)
#6 /var/www/nextcloud/core/Command/User/Delete.php(64): OC\User\User->delete()
#7 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(264): OC\Core\Command\User\Delete->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/nextcloud/3rdparty/symfony/console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\User\Delete), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/nextcloud/lib/private/Console/Application.php(173): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/nextcloud/console.php(90): OC\Console\Application->run()
#13 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#14 {main}
```
My Nextcloud version is 13.0.4, Circle 0.14.0 and PostgreSQL 9.5

**Comment by daita** [comment]
@splitt3r should have a look to this.

It seems that if you delete a user, Mindmaps will try to get listCircles using the current usersession, and will fail.

You can specify a userId to the listCircles($type, $name = '', $level = 0, $userId = '');

**Comment by splitt3r** [comment]
Yep i´m running a postDelete hook https://github.com/splitt3r/mindmaps/blob/master/lib/AppInfo/Application.php#L64-L73 and querying circles via https://github.com/splitt3r/mindmaps/blob/master/lib/Db/MindmapMapper.php#L128-L135. @Emi94 coulld you recreate the issue in the mindmaps repo? I will have a look at it.

**Comment by daita** [comment]
closing this ticket as not fully related to Circles
