### ISSUE TITLE
User session is not defined when running a dav cronjob

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/circles#483]
Nextcloud 19.0.1
Circles 0.19.5

Using `occ dav:send-event-reminders`, but I guess a regular cronjob would trigger the same behaviour.

```
An unhandled exception has been thrown:
TypeError: Argument 2 passed to OCA\Circles\Db\CirclesRequest::getCircle() must be of the type string, null given, called in /var/www/nextcloud/apps/circles/lib/Service/CirclesService.php on line 271 and defined in /var/www/nextcloud/apps/circles/lib/Db/CirclesRequest.php:192
Stack trace:
#0 /var/www/nextcloud/apps/circles/lib/Service/CirclesService.php(271): OCA\Circles\Db\CirclesRequest->getCircle('29e0016978b7d2', NULL, 1, '', true)
#1 /var/www/nextcloud/apps/circles/lib/Api/v1/Circles.php(266): OCA\Circles\Service\CirclesService->detailsCircle('29e0016978b7d2', true)
#2 /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Principal.php(480): OCA\Circles\Api\v1\Circles::detailsCircle('29e0016978b7d2', true)
#3 /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Principal.php(178): OCA\DAV\Connector\Sabre\Principal->circleToPrincipal('29e0016978b7d2')
#4 /var/www/nextcloud/apps/dav/lib/DAV/Sharing/Backend.php(200): OCA\DAV\Connector\Sabre\Principal->getPrincipalByPath('principals/circ...')
#5 /var/www/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php(2316): OCA\DAV\DAV\Sharing\Backend->getShares(198678)
#6 /var/www/nextcloud/apps/dav/lib/CalDAV/Reminder/ReminderService.php(496): OCA\DAV\CalDAV\CalDavBackend->getShares(198678)
#7 /var/www/nextcloud/apps/dav/lib/CalDAV/Reminder/ReminderService.php(142): OCA\DAV\CalDAV\Reminder\ReminderService->getAllUsersWithWriteAccessToCalendar(198678)
#8 /var/www/nextcloud/apps/dav/lib/Command/SendEventReminders.php(83): OCA\DAV\CalDAV\Reminder\ReminderService->processReminders()
#9 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\DAV\Command\SendEventReminders->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\DAV\Command\SendEventReminders), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#15 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#16 {main}
```

Did a `if ($this->userId === null) return;` in `CirclesService::detailsCircle` before `CirclesRequest::getCircle` is called to avoid this, but a proper fix based on #444 should be better.

**Comment by alex1702** [comment]
same problem.
```json
{
"reqId":"EymQX5C3RjzefR1Dc2W4",
"level":3,
"time":"2020-10-10T14:40:07+02:00",
"remoteAddr":"",
"user":"--",
"app":"core",
"method":"",
"url":"--",
"message":{
	"Exception":"TypeError",
	"Message":"Argument 2 passed to OCA\\Circles\\Db\\CirclesRequest::getCircle() must be of the type string, null given, called in /var/www/nextcloud/apps/circles/lib/Service/CirclesService.php on line 271",
	"Code":0,
	"Trace":[
		{"file":"/var/www/nextcloud/apps/circles/lib/Service/CirclesService.php","line":271,"function":"getCircle","class":"OCA\\Circles\\Db\\CirclesRequest","type":"->"},
		{"file":"/var/www/nextcloud/apps/circles/lib/Api/v1/Circles.php","line":266,"function":"detailsCircle","class":"OCA\\Circles\\Service\\CirclesService","type":"->"},
		{"file":"/var/www/nextcloud/apps/deck/lib/Service/PermissionService.php","line":266,"function":"detailsCircle","class":"OCA\\Circles\\Api\\v1\\Circles","type":"::"},
		{"file":"/var/www/nextcloud/apps/deck/lib/Activity/ActivityManager.php","line":447,"function":"findUsers","class":"OCA\\Deck\\Service\\PermissionService","type":"->"},
		{"file":"/var/www/nextcloud/apps/deck/lib/Activity/ActivityManager.php","line":262,"function":"sendToUsers","class":"OCA\\Deck\\Activity\\ActivityManager","type":"->"},
		{"file":"/var/www/nextcloud/apps/deck/lib/Cron/CardDescriptionActivity.php","line":58,"function":"triggerEvent","class":"OCA\\Deck\\Activity\\ActivityManager","type":"->"},
		{"file":"/var/www/nextcloud/lib/private/BackgroundJob/Job.php","line":62,"function":"run","class":"OCA\\Deck\\Cron\\CardDescriptionActivity","type":"->"},
		{"file":"/var/www/nextcloud/cron.php","line":126,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"}
	],
	"File":"/var/www/nextcloud/apps/circles/lib/Db/CirclesRequest.php",
	"Line":192,
	"CustomMessage":"Error while running background job (class: OCA\\Deck\\Cron\\CardDescriptionActivity, arguments: )"
},
"userAgent":"--",
"version":"19.0.4.2",
"id":"5f81ac7b9097b"
}
```

**Comment by joshtrichards** [comment]
Possibly addressed by #566

**Comment by joshtrichards** [comment]
Fixed in #566
