### ISSUE TITLE
Stack trace when using `occ dav:remove-invalid-shares`

### ISSUE THREAD

**Issue by hertz879** [nextcloud/circles#506]
When I try to use `occ dav:remove-invalid-shares` I get the following stack trace:

```
root@cloud:~# nextcloud_occ dav:remove-invalid-shares
An unhandled exception has been thrown:
TypeError: Argument 2 passed to OCA\Circles\Db\CirclesRequest::getCircle() must be of the type string, null given, called in /var/www/nextcloud/apps/circles/lib/Service/CirclesService.php on line 271 and defined in /var/www/nextcloud/apps/circles/lib/Db/CirclesRequest.php:192
Stack trace:
#0 /var/www/nextcloud/apps/circles/lib/Service/CirclesService.php(271): OCA\Circles\Db\CirclesRequest->getCircle()
#1 /var/www/nextcloud/apps/circles/lib/Api/v1/Circles.php(266): OCA\Circles\Service\CirclesService->detailsCircle()
#2 /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Principal.php(484): OCA\Circles\Api\v1\Circles::detailsCircle()
#3 /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Principal.php(182): OCA\DAV\Connector\Sabre\Principal->circleToPrincipal()
#4 /var/www/nextcloud/apps/dav/lib/Command/RemoveInvalidShares.php(68): OCA\DAV\Connector\Sabre\Principal->getPrincipalByPath()
#5 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\DAV\Command\RemoveInvalidShares->execute()
#6 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run()
#7 /var/www/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand()
#8 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun()
#9 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#10 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#11 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#12 {main}root@cloud:~# 
```

Nextcloud version is 19.0.4 running on a vm installed with the Nextcloud install script.

**Comment by hertz879** [comment]
Just noticed this also happens with `occ deck:export user-id`

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

Closing in favour of https://github.com/nextcloud/circles/issues/483.
