### ISSUE TITLE
circles app 0.20.6 won't start after update to nextcloud 20

### ISSUE THREAD

**Issue by chubber147** [nextcloud/circles#541]
Hi
app does not start after updating to nextcloud 20 using the dockerimage nextcloud:20 .

php occ app:enable circles

< An unhandled exception has been thrown:
TypeError: Return value of OCA\Circles\Service\ConfigService::getLocalInstance() must be of the type string, null returned in /var/www/html/apps/circles/lib/Service/ConfigService.php:560
Stack trace:
#0 /var/www/html/apps/circles/lib/Service/ConfigService.php(576): OCA\Circles\Service\ConfigService->getLocalInstance()
#1 /var/www/html/apps/circles/lib/Db/MembersRequest.php(654): OCA\Circles\Service\ConfigService->isLocalInstance('')
#2 /var/www/html/apps/circles/lib/Migration/RemoveDeadShares.php(111): OCA\Circles\Db\MembersRequest->removeMember(Object(OCA\Circles\Model\Member))
#3 /var/www/html/lib/private/Repair.php(111): OCA\Circles\Migration\RemoveDeadShares->run(Object(OC\Repair))
#4 /var/www/html/lib/private/legacy/OC_App.php(1042): OC\Repair->run()
#5 /var/www/html/lib/private/Installer.php(160): OC_App::executeRepairSteps('circles', Array)
#6 /var/www/html/core/Command/App/Enable.php(123): OC\Installer->installApp('circles', false)
#7 /var/www/html/core/Command/App/Enable.php(93): OC\Core\Command\App\Enable->enableApp('circles', Array, false, Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Enable->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Enable), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/console.php(100): OC\Console\Application->run()
#14 /var/www/html/occ(11): require_once('/var/www/html/c...')>

output of: php occ app:check-code circles:

<Analysing /var/www/html/apps/circles/files/list.php
 2 errors
    line    3: OCP\User - Static method of deprecated class must not be called
    line    3: OCP\User::checkLoggedIn - Method of deprecated class must not be called
Analysing /var/www/html/apps/circles/lib/GlobalScale/AGlobalScaleEvent.php
 2 errors
    line  255: != - is discouraged
    line  256: != - is discouraged
App is not compliant>

our 1000 users use the this app very often.

**Comment by chubber147** [comment]
Hi, 
I changed the config.php:
 'overwrite.cli.url' => 'example.com', to 'https://example.com',

followed an tip from #475 

circles-app now working

cheers
