### ISSUE TITLE
Error: Call to a member function getUID() on null in Circles.php:202

### ISSUE THREAD

**Issue by timm2k** [nextcloud/circles#560]
Hi,

I've some trouble with Deck when Circles app is enabled.

`sudo -u nginx ./occ deck:export timm` 
```
An unhandled exception has been thrown:
Error: Call to a member function getUID() on null in /var/www/data/html/nextcloud/apps/circles/lib/Api/v1/Circles.php:202
Stack trace:
#0 /var/www/data/html/nextcloud/apps/circles/lib/Api/v1/Circles.php(222): OCA\Circles\Api\v1\Circles::listCircles(15, '', 1, '', true)
#1 /var/www/data/html/nextcloud/apps/deck/lib/Db/BoardMapper.php(162): OCA\Circles\Api\v1\Circles::joinedCircles('', true)
#2 /var/www/data/html/nextcloud/apps/deck/lib/Service/BoardService.php(120): OCA\Deck\Db\BoardMapper->findAllByCircles('timm', NULL, NULL, -1, true)
#3 /var/www/data/html/nextcloud/apps/deck/lib/Service/BoardService.php(130): OCA\Deck\Service\BoardService->getUserBoards(-1, true)
#4 /var/www/data/html/nextcloud/apps/deck/lib/Command/UserExport.php(90): OCA\Deck\Service\BoardService->findAll()
#5 /var/www/data/html/nextcloud/apps/bookmarks/vendor/symfony/console/Command/Command.php(255): OCA\Deck\Command\UserExport->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/data/html/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/data/html/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Deck\Command\UserExport), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/data/html/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/data/html/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/data/html/nextcloud/console.php(100): OC\Console\Application->run()
#11 /var/www/data/html/nextcloud/occ(11): require_once('/var/www/data/h...')
#12 {main}
```

I get this on two instances with Nexcloud 20.0.8RC1 + Circles 0.20.6 and Nextcloud 19.0.8 + circles 0.19.11.

Any ideas?

Kind regards 
Timm

**Comment by timm2k** [comment]
Same for Nextcloud 21 + Circles 0.20.6.

**Comment by daita** [comment]
Hello again timm!

As said already, we are investigating :)

**Comment by daita** [comment]
I will close this ticket as it has be discussed with Julius that the issue comes from the Deck app

**Comment by grossherr** [comment]
@daita Where has this been discussed? It also breaks the access to shares via link. If either deck or circles is disabled, then it works again.

**Comment by daita** [comment]
https://github.com/nextcloud/deck/pull/2823
