### ISSUE TITLE
Error code 500 https://mynextcloud.com/apps/circles/v1/circles from link [NC19][circles: 0.19.12]

### ISSUE THREAD

**Issue by gorsing** [nextcloud/circles#564]
I get error code 500 https://mynextcloud.com/apps/circles/v1/circles from link [NC19][circles: 0.19.12]
and CSRF check failed
how to diagnose the problem

**Comment by gorsing** [comment]
```
sudo -u apache php occ app:list
PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
Enabled:
  - activity: 2.12.1
  - calendar: 2.0.5
  - circles: 0.19.12
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - drawio: 0.9.9
  - federatedfilesharing: 1.9.0
  - files: 1.14.0
  - files_fulltextsearch: 1.4.3
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - fulltextsearch: 1.4.2
  - fulltextsearch_elasticsearch: 1.5.2
  - icdcsupport: 0.0.1
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - onlyoffice: 6.2.0
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - settings: 1.1.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - user_ldap: 1.9.1
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - accessibility
  - admin_audit
  - encryption
  - federation
  - files_external
  - nextcloud_announcements
  - password_policy
  - serverinfo
  - sharebymail
  - support
  - survey_client
  - updatenotification
```

```
[root@prod-server]# sudo -u apache php occ circles:test
PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
An unhandled exception has been thrown:
Error: Call to undefined method daita\MySmallPhpTools\Model\Request::type() in /var/www/html/nextcloud/apps/circles/lib/Command/CirclesTest.php:197
Stack trace:
#0 /var/www/html/nextcloud/apps/circles/lib/Command/CirclesTest.php(131): OCA\Circles\Command\CirclesTest->testRequest(Object(Symfony\Component\Console\Output\ConsoleOutput), 'GET', 'core.CSRFToken....')
#1 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Circles\Command\CirclesTest->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1012): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Circles\Command\CirclesTest), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/nextcloud/console.php(100): OC\Console\Application->run()
#8 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
#9 {main}[root@prod-server]#
```

**Comment by gorsing** [comment]
I have app federation disabled. I will include it in the upcoming announced works on the server. And I can gather more information.

**Comment by gorsing** [comment]
./vendor/daita/my-small-php-tools/lib/Model/Nextcloud/NC19Request.php

Not found basedOnUrl()

Technical details

    Remote Address: 172.20.9.48
    Request ID: YEno9tNcUiH4UkClltZVUgAAAAM
    Type: Exception
    Code: 0
    Message: Call to undefined method daita\MySmallPhpTools\Model\Nextcloud\NC19Request::basedOnUrl()
    File: /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php
    Line: 110


Trace

#0 /var/www/html/nextcloud/lib/private/AppFramework/App.php(137): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Circles\Controller\CirclesController), 'destroy')
#1 /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OCA\\Circles\\Con...', 'destroy', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#2 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#3 /var/www/html/nextcloud/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#4 /var/www/html/nextcloud/lib/base.php(1010): OC\Route\Router->match('/apps/circles/v...')
#5 /var/www/html/nextcloud/index.php(37): OC::handleRequest()
#6 {main}

**Comment by joshtrichards** [comment]
Duplicate of #524
