### ISSUE TITLE
Cannot `occ files:scan --all` Exception during scan: FederatedUser must be local (nc22)

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/circles#601]
Nextcloud: 22 beta 2
Circles: master

1. Have multiple users
2. Do an `occ files:scan --all`
3. See error in console

```
Exception during scan: FederatedUser must be local
  #0 /var/www/nextcloud/apps2/circles/lib/Service/FederatedUserService.php(696): OCA\Circles\Service\FederatedUserService->getSingleCircle(Object(OCA\Circles\Model\FederatedUser))
  #1 /var/www/nextcloud/apps2/circles/lib/Service/FederatedUserService.php(332): OCA\Circles\Service\FederatedUserService->fillSingleCircleId(Object(OCA\Circles\Model\FederatedUser))
  #2 /var/www/nextcloud/apps2/circles/lib/ShareByCircleProvider.php(512): OCA\Circles\Service\FederatedUserService->getLocalFederatedUser('Test05')
  #3 /var/www/nextcloud/lib/private/Share20/Manager.php(1353): OCA\Circles\ShareByCircleProvider->getSharedWith('Test05', 7, NULL, -1, 0)
  #4 /var/www/nextcloud/apps/files_sharing/lib/MountProvider.php(80): OC\Share20\Manager->getSharedWith('Test05', 7, NULL, -1)
  #5 /var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php(119): OCA\Files_Sharing\MountProvider->getMountsForUser(Object(OC\User\User), Object(OC\Files\Storage\StorageFactory))
  #6 /var/www/nextcloud/lib/private/Files/Filesystem.php(452): OC\Files\Config\MountProviderCollection->addMountForUser(Object(OC\User\User), Object(OC\Files\Mount\Manager))
  #7 /var/www/nextcloud/lib/private/Files/Filesystem.php(377): OC\Files\Filesystem::initMountPoints('Test05')
  #8 /var/www/nextcloud/lib/private/legacy/OC_Util.php(325): OC\Files\Filesystem::init('Test05', '/Test05/files')
  #9 /var/www/nextcloud/lib/private/Files/Utils/Scanner.php(116): OC_Util::setupFS('Test05')
  #10 /var/www/nextcloud/lib/private/Files/Utils/Scanner.php(202): OC\Files\Utils\Scanner->getMounts('/Test05')
  #11 /var/www/nextcloud/apps/files/lib/Command/Scan.php(158): OC\Files\Utils\Scanner->scan('/Test05', true, NULL)
  #12 /var/www/nextcloud/apps/files/lib/Command/Scan.php(214): OCA\Files\Command\Scan->scanFiles('Test05', '/Test05', Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
  #13 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #14 /var/www/nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #15 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #16 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #17 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #18 /var/www/nextcloud/lib/private/Console/Application.php(210): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #19 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
  #20 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
  #21 {main}
```

**Comment by daita** [comment]
fixed in https://github.com/nextcloud/circles/commit/07d75b0cff2a59a98616958f456fd79e85b200a2
