### ISSUE TITLE
FederatedEvent::getMember() must be an instance of OCA\Circles\Model\Member, null returned

### ISSUE THREAD

**Issue by blizzz** [nextcloud/circles#663]
I got following exception after running `sudo -u www-data php /var/www/html/occ user:info $UID` on cli on 22 RC 2. This was triggered after the email of a user was updated and the hooks were emitted.

```
TypeError: Return value of OCA\Circles\Model\Federated\FederatedEvent::getMember() must be an instance of OCA\Circles\Model\Member, null returned in /var/www/html/apps/circles/lib/Model/Federated/FederatedEvent.php:338
Stack trace:
#0 /var/www/html/apps/circles/lib/Events/CircleMemberGenericEvent.php(59): OCA\Circles\Model\Federated\FederatedEvent->getMember()
#1 /var/www/html/apps/circles/lib/Events/EditingCircleMemberEvent.php(74): OCA\Circles\Events\CircleMemberGenericEvent->__construct()
#2 /var/www/html/apps/circles/lib/Service/EventService.php(252): OCA\Circles\Events\EditingCircleMemberEvent->__construct()
#3 /var/www/html/apps/circles/lib/FederatedItems/MemberDisplayName.php(134): OCA\Circles\Service\EventService->memberNameEditing()
#4 /var/www/html/apps/circles/lib/Service/FederatedEventService.php(182): OCA\Circles\FederatedItems\MemberDisplayName->manage()
#5 /var/www/html/apps/circles/lib/Listeners/DeprecatedListener.php(129): OCA\Circles\Service\FederatedEventService->newEvent()
#6 /var/www/html/apps/circles/lib/AppInfo/Application.php(161): OCA\Circles\Listeners\DeprecatedListener->userAccountUpdated()
#7 /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php(264): OCA\Circles\AppInfo\Application->OCA\Circles\AppInfo\{closure}()
#8 /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()
#9 /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#10 /var/www/html/lib/private/EventDispatcher/SymfonyAdapter.php(123): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#11 /var/www/html/lib/private/Accounts/AccountManager.php(240): OC\EventDispatcher\SymfonyAdapter->dispatch()
#12 /var/www/html/lib/private/Accounts/AccountManager.php(654): OC\Accounts\AccountManager->updateUser()
#13 /var/www/html/lib/private/Accounts/Hooks.php(69): OC\Accounts\AccountManager->updateAccount()
#14 /var/www/html/lib/private/Accounts/Hooks.php(77): OC\Accounts\Hooks->changeUserHook()
#15 /var/www/html/lib/private/EventDispatcher/ServiceEventListener.php(75): OC\Accounts\Hooks->handle()
#16 /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php(251): OC\EventDispatcher\ServiceEventListener->__invoke()
#17 /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#18 /var/www/html/lib/private/EventDispatcher/EventDispatcher.php(88): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#19 /var/www/html/lib/private/EventDispatcher/EventDispatcher.php(100): OC\EventDispatcher\EventDispatcher->dispatch()
#20 /var/www/html/lib/private/Server.php(621): OC\EventDispatcher\EventDispatcher->dispatchTyped()
#21 [internal function]: OC\Server->OC\{closure}()
#22 /var/www/html/lib/private/Hooks/EmitterTrait.php(106): call_user_func_array()
#23 /var/www/html/lib/private/Hooks/PublicEmitter.php(40): OC\Hooks\BasicEmitter->emit()
#24 /var/www/html/lib/private/User/User.php(493): OC\Hooks\PublicEmitter->emit()
#25 /var/www/html/lib/private/User/User.php(182): OC\User\User->triggerChange()
#26 /var/www/html/apps/user_ldap/lib/User/User.php(453): OC\User\User->setEMailAddress()
#27 /var/www/html/apps/user_ldap/lib/User/User.php(207): OCA\User_LDAP\User\User->updateEmail()
#28 /var/www/html/apps/user_ldap/lib/Access.php(927): OCA\User_LDAP\User\User->processAttributes()
#29 /var/www/html/apps/user_ldap/lib/Command/CheckUser.php(163): OCA\User_LDAP\Access->batchApplyUserAttributes()
#30 /var/www/html/apps/user_ldap/lib/Command/CheckUser.php(98): OCA\User_LDAP\Command\CheckUser->updateUser()
#31 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\User_LDAP\Command\CheckUser->execute()
#32 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#33 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#34 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#35 /var/www/html/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run()
#36 /var/www/html/console.php(99): OC\Console\Application->run()
#37 /var/www/html/occ(11): require_once('/var/www/html/c...')
#38 {main}
```

@ArtificialOwl

**Comment by ArtificialOwl** [comment]
Ok, I don't have any LDAP ready but it seems that running `./occ user:info` with LDAP will get the data from LDAP and update locally if needed, then trigger the event...

Then, we have 2 issues:
- first is that on non-LDAP the displayName were not blocked behind a faulty condition
- then the issue you reported.

I am on it !
