### ISSUE TITLE
`ConfigService->linkToRoute()`: `rtrim() expects parameter 1 to be string, null given`

### ISSUE THREAD

**Issue by mejo-** [nextcloud/circles#774]
Since commit 169118a9be2a51bda9977b8eb4aa92ae3fc0e786 ("include and config path in loopback"), occ commands that trigger `ConfigService->getLoopbackPath()` cause an exception:

```
$ php occ group:adduser "Bobs Group" "jane"
string(28) "https://nextcloud.local/test"
An unhandled exception has been thrown:
TypeError: rtrim() expects parameter 1 to be string, null given in /var/www/html/apps/circles/lib/Service/ConfigService.php:699
Stack trace:
#0 /var/www/html/apps/circles/lib/Service/ConfigService.php(699): rtrim(NULL, '/')
#1 /var/www/html/apps/circles/lib/Service/ConfigService.php(529): OCA\Circles\Service\ConfigService->linkToRoute('circles.EventWr...', Array)
#2 /var/www/html/apps/circles/lib/Service/ConfigService.php(667): OCA\Circles\Service\ConfigService->getLoopbackPath('circles.EventWr...', Array)
#3 /var/www/html/apps/circles/lib/Service/FederatedEventService.php(421): OCA\Circles\Service\ConfigService->configureLoopbackRequest(Object(ArtificialOwl\MySmallPhpTools\Model\Nextcloud\nc22\NC22Request), 'circles.EventWr...', Array)
#4 /var/www/html/apps/circles/lib/Service/FederatedEventService.php(181): OCA\Circles\Service\FederatedEventService->initBroadcast(Object(OCA\Circles\Model\Federated\FederatedEvent))
#5 /var/www/html/apps/circles/lib/Service/SyncService.php(450): OCA\Circles\Service\FederatedEventService->newEvent(Object(OCA\Circles\Model\Federated\FederatedEvent))
#6 /var/www/html/apps/circles/lib/Listeners/GroupMemberAdded.php(73): OCA\Circles\Service\SyncService->groupMemberAdded('Bobs Group', 'jane')
#7 /var/www/html/lib/private/EventDispatcher/ServiceEventListener.php(87): OCA\Circles\Listeners\GroupMemberAdded->handle(Object(OCP\Group\Events\UserAddedEvent))
#8 /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php(251): OC\EventDispatcher\ServiceEventListener->__invoke(Object(OCP\Group\Events\UserAddedEvent), 'OCP\\Group\\Event...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#9 /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'OCP\\Group\\Event...', Object(OCP\Group\Events\UserAddedEvent))
#10 /var/www/html/lib/private/EventDispatcher/EventDispatcher.php(88): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(OCP\Group\Events\UserAddedEvent), 'OCP\\Group\\Event...')
#11 /var/www/html/lib/private/EventDispatcher/EventDispatcher.php(100): OC\EventDispatcher\EventDispatcher->dispatch('OCP\\Group\\Event...', Object(OCP\Group\Events\UserAddedEvent))
#12 /var/www/html/lib/private/Server.php(484): OC\EventDispatcher\EventDispatcher->dispatchTyped(Object(OCP\Group\Events\UserAddedEvent))
#13 [internal function]: OC\Server->OC\{closure}(Object(OC\Group\Group), Object(OC\User\User))
#14 /var/www/html/lib/private/Hooks/EmitterTrait.php(106): call_user_func_array(Object(Closure), Array)
#15 /var/www/html/lib/private/Hooks/PublicEmitter.php(40): OC\Hooks\BasicEmitter->emit('\\OC\\Group', 'postAddUser', Array)
#16 /var/www/html/lib/private/Group/Group.php(196): OC\Hooks\PublicEmitter->emit('\\OC\\Group', 'postAddUser', Array)
#17 /var/www/html/core/Command/Group/AddUser.php(75): OC\Group\Group->addUser(Object(OC\User\User))
#18 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Group\AddUser->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Group\AddUser), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/console.php(99): OC\Console\Application->run()
#25 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

That's because `parse_url()` in `$knownPath = parse_url($this->config->getSystemValue('overwrite.cli.url'), PHP_URL_PATH);` in `ConfigService->linkToRoute()` returns null if `PHP_URL_PATH` doesn't exist.

I'll open a PR to fix this.

**Comment by patzm** [comment]
nice thanks for fixing this, I also ran into it.
